name: Publish to Nuget.org
# This workflow is triggered on pushes to the repository.
on: 
  push:
    branches:
      - master

jobs:
  build:
    # Job name is Greeting
    name: Publish
    # This job runs on Linux
    runs-on: windows-latest
    steps:
      # This step uses GitHub's hello-world-javascript-action: https://github.com/actions/hello-world-javascript-action
      - name: Checkout
        uses: actions/checkout@v2
        id: checkout
      - name: Install Cake-Tool
        run: dotnet tool install -g Cake.Tool
        id: cake-tool
      - name: Install Xamarin.AndroidBinderator.Tool
        run: dotnet tool install -g Xamarin.AndroidBinderator.Tool
        id: xamarin-androidbinderator-tool
      - name: Run Cake script
        run: dotnet cake
        id: dotnet-cake
      - name: Publish
        run: dotnet nuget push ./output/*.nupkg
             --api-key ${{secrets.NUGET_DEPLOY_KEY}}
             --source https://api.nuget.org/v3/index.json
